### ISSUE TITLE
Document that sprig-reap supports AR relations

### ISSUE THREAD

**Issue by AndrewSwerlick** [vigetlabs/sprig-reap#18]
As far as I can tell from reviewing the code and writing some additional tests, sprig-reap supports supplying AR relations for the list of models to reap, and then only reaping models returned by those relations. Is there any reason this isn't called out in the documentation? Is this just a coincidence of implementation that my not be supported going forward, or a true feature? If the latter, perhaps some documentation can be added to the README noting as much?

**Comment by h0tl33t** [comment]
This is now implemented and documented -- thanks!
