### ISSUE TITLE
How to load generated yml-files for habtm associations with sprig?

### ISSUE THREAD

**Issue by OneDivZero** [vigetlabs/sprig-reap#19]
Sprig-Reap created also yml-files for habtm-association-tables like this example below. But Sprig requires in seeds.rb to specify a classname. So what's the benefit of having this generated files? How can I use them meaningfully?

records:
- sprig_id: 
  package_id: 1
  station_id: "<%= sprig_record(PayTv::Station, 1).id %>"
- sprig_id: 
  package_id: 2
  station_id: "<%= sprig_record(PayTv::Station, 1).id %>"

**Comment by h0tl33t** [comment]
Currently, Sprig-Reap doesn't support has-and-belongs-to-many associations.  Thanks for opening an issue -- I'll look into this.

**Comment by h0tl33t** [comment]
@OneDivZero -- I've implemented HABTM support in the newest version (0.1.0).  Give it a shot and let me know how it works for you.
