### ISSUE TITLE
does sprig-reap work with latest ruby/rails?

### ISSUE THREAD

**Issue by bitterloa** [vigetlabs/sprig-reap#22]
Hi, I was previously running both sprig and sprig-reap OK but lately I am getting errors even when trying to do the simplest reap task. The only thing I can think of is that perhaps before I was using a different version of ruby and/or rails. My current version of ruby is 2.2.0 and rails 4.2.0.

Right now if I run `rake db:seed:reap` it quickly shows "Finished reaping!" but doesn't create any files although there's definitely data in the database. And if I try and specify options and say limit to just my User model I get the following nil error. Other models throw errors as well and it almost feels like the errors occur because I require many of my models to be linked to a user record (i.e. user_id cannot be null). 

`rake db:seed:reap TARGET_ENV=development MODELS=User

D, [2015-03-18T06:10:57.471191 #86792] DEBUG -- : Reaping records from the database...
rake aborted!
NoMethodError: undefined method `-' for nil:NilClass
/Users/dude/.rvm/gems/ruby-2.2.0@tigerwod/gems/sprig-reap-0.2.0/lib/sprig/reap/tsortable_hash.rb:20:in `block (2 levels) in resolve_circular_habtm_dependencies!'`

**Comment by Fosome** [comment]
Thanks, looking into this.

**Comment by Fosome** [comment]
I just created a simple app on 2.2.1p85 and rails 4.2 that ran with no issues.

It may be the complexity of your models, as you say.  Can you share more information, or a link to the app source?

**Comment by bitterloa** [comment]
Thanks for the reply, I think you are correct that it may be an issue with recent validations or database constraints I've added to my models--nearly all of my models need to belong to a User so have a user_id field. In the rails model.rb I added validation constraints for this and there are also "allow_null: false" constraints on the user_id column for these tables in the database. And I've added this since the last time I used sprig-reap. Above is the error I get when just trying to sprig-reap the User table alone, but I'm unsure why I'm seeing the undefined '-' for nil:NilClass error here--perhaps because the User model also has a HABTM relationship to the Roles class? 

Other tables that need to belong to a User fail with:
`KeyError: key not found: User(id: integer, email: string, password_digest: string, disa...`

I'm just not sure how to create a yml file even from a single table at this point. I do have one table that doesn't depend on User now that I am able to export using sprig-reap though. Let me know if I can do more testing.

Also, I'll let you know that I am actually just doing some testing on my own right now to see if I can use Sprig to create 'factories' in my tests -- I have just had it with FactoryGirl and other methods, even after years it's never worked well for me but the way Sprig is just feels much better for me. I realize this wasn't it's original purpose, but if I get it up and running again I'll let you know how my testing goes! :-)

**Comment by sschafft** [comment]
I am also showing this issue on Ruby 2.2.1 / Rails 4.2 and my models in question also have HABTM relationships. (`undefined method -' for nil:NilClass`)

**Comment by bitterloa** [comment]
@sschafft do your models with habtm relationships have either model validation or database restraints on the relationships? i don't think the issue is limited to habtm relationships as it occurs for me with simple has_many/belongs_to relationships (basically any models I have that belong_to User). But I also have validations that ensure that user_id is never nil for saved records and validations as well...

**Comment by sschafft** [comment]
Hmm... interesting. I didnt test around that. But no as of right now I havent gone through adding all the validations that will be there so there aren't any validations as of yet.

**Comment by h0tl33t** [comment]
Sorry it took me so long to get to this.  I recently added HABTM support to Sprig-Reap, but didn't account for the use case where a user supplies only one side of the HABTM relationship when reaping records.

With version `0.3.0`, the code that deals with resolving circular dependencies with HABTM associations now makes a presence check to ensure both sides of the relationship are in the model list before attempting any resolution.

Let me know if you're still seeing any issues related to this.  Thanks for bringing this to our attention!
